import requests
import os
import pandas as pd
import sqlalchemy as db

engine = db.create_engine('sqlite:///mydatabase.db')

df_ticker_symbols = pd.read_csv('./stocks-list.csv')

# SQLite connection (replace 'sqlite:///mydatabase.db' with your desired database connection string)
engine = db.create_engine('sqlite:///mydatabase.db')

# Store the DataFrame in a SQL table (replace 'news_sentiment' with your preferred table name)
df_ticker_symbols.to_sql('Ticker_Symbols', con=engine, if_exists='replace', index=False)

class StockFinder:

    def by_symbol(self, symbol):
        uppercaseSymbol = str(symbol).upper()
        query = f'SELECT * FROM Ticker_Symbols WHERE Symbol="{uppercaseSymbol}"'
        return pd.read_sql_query(query, engine)

    def by_name(self, name):
        query = f'SELECT * FROM Ticker_Symbols WHERE "Company Name" LIKE"{name}%"'
        print(name)
        return pd.read_sql_query(query, engine)

    def by_market_cap_range(self, min_cap, max_cap):
        # Implement sentiment analysis algorithm here
        pass
    
    def by_industry(self, industry):
        query = f'SELECT * FROM Ticker_Symbols WHERE Industry="{industry}"'
        return pd.read_sql_query(query, engine)
    
    def fetch_all_industries(self):
        query = f'SELECT DISTINCT Industry FROM Ticker_Symbols'
        return pd.read_sql_query(query, engine)
    
    def find_sentiment_score(self, ticker):
        formattedTicker = str(ticker).upper()
        query = f'SELECT "Market Cap" FROM Ticker_Symbols WHERE Symbol="{formattedTicker}"'
        # logic to find ticker score here
        # make API Call using the ticker symbol and time frame of last one year
        return pd.read_sql_query(query, engine)


class APIResponseFetcher():
    
    def by_symbol(self, symbol):
        api_key = 'demo'
        url = f"https://www.alphavantage.co/query?function=NEWS_SENTIMENT&tickers={symbol}&apikey={api_key}"
        return requests.get(url).json()
    
    def by_topic(self, topic):
        # api_key = 'demo'
        # url = f"https://www.alphavantage.co/query?function=NEWS_SENTIMENT&topics={topic}&apikey={api_key}"
        # return requests.get(url).json()
        return dummyNewsData
    

dummyNewsData = {'items': '50',
 'sentiment_score_definition': 'x <= -0.35: Bearish; -0.35 < x <= -0.15: Somewhat-Bearish; -0.15 < x < 0.15: Neutral; 0.15 <= x < 0.35: Somewhat_Bullish; x >= 0.35: Bullish',
 'relevance_score_definition': '0 < x <= 1, with a higher score indicating higher relevance.',
 'feed': [{'title': "Change This 'Palworld' Setting Until Pocket Pair Fixes Things",
   'url': 'https://www.forbes.com/sites/paultassi/2024/01/27/change-this-palworld-setting-until-pocket-pair-fixes-things/',
   'time_published': '20240127T150527',
   'authors': ['Paul Tassi'],
   'summary': 'I previously wrote about a bunch of problems that Palworld has as an early access game, but one stands out in terms of moment to moment gameplay.',
   'banner_image': 'https://specials-images.forbesimg.com/imageserve/64592f3cfea505125d2796dd/960x0.jpg',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': -0.121706,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.069294',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Google Warns Of New Date For Gmail, Photos Deletion Part 2',
   'url': 'https://www.forbes.com/sites/daveywinder/2024/01/27/google-warns-of-surprise-new-date-for-gmail-photos-deletion-part-2/',
   'time_published': '20240127T150112',
   'authors': ['Davey Winder'],
   'summary': 'With Google having already started deleting inactive Gmail and Photo accounts in December 2023, many users have wondered when phase two of the content deletion will start. The initial round of Google account deletions only applied to those that were never used after being created at least two ...',
   'banner_image': 'https://imageio.forbes.com/specials-images/imageserve/654f4b50efd47f4a2f818335/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.059621,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.89964',
     'ticker_sentiment_score': '0.079976',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "If You Invested $1000 In Apple When The iPad Was Launched 14 Years Ago, Here's How Much You'd Have Today - Apple  ( NASDAQ:AAPL ) ",
   'url': 'https://www.benzinga.com/markets/equities/24/01/36814939/if-you-invested-1000-in-apple-when-the-ipad-was-launched-14-years-ago-heres-how-much-youd-have-t',
   'time_published': '20240127T145158',
   'authors': ['Rounak Jain'],
   'summary': 'The Apple iPad has turned 14. Launched on Jan. 27, 2010, the iPad was subject to jokes before becoming a category-defining product. Apple Inc.',
   'banner_image': 'https://cdn.benzinga.com/files/images/story/2024/Apple-iPad-Steve-Jobs.jpeg?width=1200&height=800&fit=crop',
   'source': 'Benzinga',
   'category_within_source': 'Markets',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.365926'}],
   'overall_sentiment_score': 0.274894,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '0.85804',
     'ticker_sentiment_score': '0.523604',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': "'Diablo 4' Already Patched Its Aggravating Season 3, Here's What Changed",
   'url': 'https://www.forbes.com/sites/paultassi/2024/01/27/diablo-4-already-patched-its-aggravating-season-3-heres-what-changed/',
   'time_published': '20240127T144625',
   'authors': ['Paul Tassi'],
   'summary': "Say what you will about Blizzard, but they are nothing if not responsive when it comes to people disliking certain things in Diablo 4. The reception to Diablo 4's season 3, Season of the Construct has been universally negative, and now, not even a week after launch, a big patch has already gone ...",
   'banner_image': 'https://specials-images.forbesimg.com/imageserve/6455355a770d2e0fde9c02fa/960x0.jpg',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.036339,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.08687',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Cybersecurity Is More Important Than Ever. This Unstoppable Index Fund Could Turn $200 per Month Into $236,000 With Little to No Effort',
   'url': 'https://www.fool.com/investing/2024/01/27/cybersecurity-is-more-important-than-ever-this-uns/',
   'time_published': '20240127T144200',
   'authors': ['Adam Spatacco'],
   'summary': 'Many cybersecurity stocks have generated meaningful returns for investors in recent years.',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F761763%2Ffamily-saving-money-generational-wealth.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.998287'}],
   'overall_sentiment_score': 0.297589,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.06623',
     'ticker_sentiment_score': '0.054335',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ZS',
     'relevance_score': '0.132004',
     'ticker_sentiment_score': '0.038331',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CRWD',
     'relevance_score': '0.132004',
     'ticker_sentiment_score': '0.038331',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'S',
     'relevance_score': '0.06623',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'PANW',
     'relevance_score': '0.06623',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Roku Stock Is Beaten Down Now, But It Could 10X',
   'url': 'https://www.fool.com/investing/2024/01/27/roku-stock-is-beaten-down-now-but-it-could-10x/',
   'time_published': '20240127T143300',
   'authors': ['Jeremy Bowman'],
   'summary': "The streaming leader is down 80% from its peak. Here's how it is turning around.",
   'banner_image': 'https://media.ycharts.com/charts/f549db07c2c788dbbe6b7be660a21c43.png',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.999346'},
    {'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.413559'}],
   'overall_sentiment_score': 0.287291,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'NFLX',
     'relevance_score': '0.227538',
     'ticker_sentiment_score': '0.02863',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ROKU',
     'relevance_score': '0.688485',
     'ticker_sentiment_score': '0.442959',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': "'Hogwarts Legacy' Is Finally Getting Updates And New Features In 2024",
   'url': 'https://www.forbes.com/sites/paultassi/2024/01/27/hogwarts-legacy-is-finally-getting-updates-and-new-features-in-2024/',
   'time_published': '20240127T142940',
   'authors': ['Paul Tassi'],
   'summary': 'It is just a bit weird that Hogwarts Legacy, the highest-selling game of 2023, beating out even Call of Duty, received close to no meaningful updates for the entire year of launch.',
   'banner_image': 'https://specials-images.forbesimg.com/imageserve/6455355a770d2e0fde9c02fa/960x0.jpg',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.090889,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'SNEJF',
     'relevance_score': '0.086556',
     'ticker_sentiment_score': '0.030393',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOG',
     'relevance_score': '0.086556',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "What's Going On With 'Suicide Squad: Kill The Justice League' Reviews",
   'url': 'https://www.forbes.com/sites/paultassi/2024/01/27/whats-going-on-with-suicide-squad-kill-the-justice-league-reviews/',
   'time_published': '20240127T141513',
   'authors': ['Paul Tassi'],
   'summary': "On Tuesday, Rocksteady will launch its first major game since 2015's Arkham Knight, Suicide Squad: Kill the Justice League. But if you're wondering where press and creator reviews of the game are just a few days ahead of that, you're not alone.",
   'banner_image': 'https://specials-images.forbesimg.com/imageserve/64592f3cfea505125d2796dd/960x0.jpg',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': -0.031041,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.070725',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'The future of the American amusement park in a Disney, Universal dominated world of thrills',
   'url': 'https://www.cnbc.com/2024/01/27/six-flags-future-in-a-disney-universal-dominated-theme-park-world.html',
   'time_published': '20240127T140001',
   'authors': ['Kevin Williams'],
   'summary': 'Can a merger of Six Flags and Cedar Fair give the amusement park operators a boost against much bigger, deeper-pocketed rivals at Disney and Universal?',
   'banner_image': 'https://image.cnbcfm.com/api/v1/image/107328797-16990357551699035753-31869819626-1080pnbcnews.jpg?v=1699035755&w=750&h=422&vtcrop=y',
   'source': 'CNBC',
   'category_within_source': 'Top News',
   'source_domain': 'www.cnbc.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.650727'},
    {'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.796627'}],
   'overall_sentiment_score': 0.209384,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.018201',
     'ticker_sentiment_score': '0.047052',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'FUN',
     'relevance_score': '0.351807',
     'ticker_sentiment_score': '0.260782',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'CCZ',
     'relevance_score': '0.018201',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Taking a Hard Pass on Netflix Stock? This Could Change Your Mind',
   'url': 'https://www.fool.com/investing/2024/01/27/taking-a-hard-pass-on-a-netflix-investment-this-co/',
   'time_published': '20240127T135800',
   'authors': ['Danny Vena'],
   'summary': 'Netflix has delivered four consecutive quarters of accelerating growth. Is it time to buy the stock?',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762427%2Fnetflix-la-hq.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'Financial Markets', 'relevance_score': '0.684621'},
    {'topic': 'Earnings', 'relevance_score': '0.992549'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.198623,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'NFLX',
     'relevance_score': '0.624759',
     'ticker_sentiment_score': '0.283176',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'TKO',
     'relevance_score': '0.058903',
     'ticker_sentiment_score': '0.031985',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CRYPTO:NXT',
     'relevance_score': '0.058903',
     'ticker_sentiment_score': '0.031985',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Is There a Silver Lining in VinFast Auto's Disappointing Q4 Deliveries?",
   'url': 'https://www.fool.com/investing/2024/01/27/silver-lining-vinfast-auto-disappoint-deliveries/',
   'time_published': '20240127T132700',
   'authors': ['Daniel Miller'],
   'summary': "VinFast's Q4 and full-year deliveries are a mix of good and bad. Here's what you need to know.",
   'banner_image': 'https://g.foolcdn.com/editorial/images/762305/vf3.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.161647'}],
   'overall_sentiment_score': 0.169809,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'VFS',
     'relevance_score': '0.146025',
     'ticker_sentiment_score': '0.162528',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Saturday morning cartoons, streaming anytime: Why kids content is vital to subscriber growth',
   'url': 'https://www.cnbc.com/2024/01/27/kids-streaming-content-vital-to-subscriber-growth.html',
   'time_published': '20240127T130002',
   'authors': ['Sarah Whitten'],
   'summary': "The unique thing about kids content is that streamers don't need a lot of it to keep kids occupied.",
   'banner_image': 'https://image.cnbcfm.com/api/v1/image/107365313-1706302440371-gettyimages-521007327-20141016181215_589_IMG_4397JPG_133292.jpeg?v=1706302533&w=1920&h=1080',
   'source': 'CNBC',
   'category_within_source': 'Business',
   'source_domain': 'www.cnbc.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.495866'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.187148,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'NFLX',
     'relevance_score': '0.035714',
     'ticker_sentiment_score': '0.098722',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOG',
     'relevance_score': '0.035714',
     'ticker_sentiment_score': '0.05888',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CCZ',
     'relevance_score': '0.035714',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Block Stock: Buy, Sell, or Hold?',
   'url': 'https://www.fool.com/investing/2024/01/27/block-stock-buy-sell-or-hold/',
   'time_published': '20240127T125000',
   'authors': ['Neil Patel'],
   'summary': 'Investors will find no shortage of reasons to like this fintech business.',
   'banner_image': 'https://g.foolcdn.com/editorial/images/762239/person-using-square-block-device-behind-counter-while-square-block-device-logo-is-in-view_block.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.929393'}],
   'overall_sentiment_score': 0.17594,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'SQ',
     'relevance_score': '0.478939',
     'ticker_sentiment_score': '0.264853',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'A tattoo artist specializing in Disney designs shares her tips for getting ink inspired by characters, TV shows, and movies',
   'url': 'https://www.businessinsider.com/tattoo-tips-disney-designs-from-artist-2023-12',
   'time_published': '20240127T122900',
   'authors': ['Amber Wainwright'],
   'summary': 'Tattoo artist: Best tips for getting Disney tattoos - Business Insider ...',
   'banner_image': None,
   'source': 'Business Insider',
   'category_within_source': 'GoogleRSS',
   'source_domain': 'www.businessinsider.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.282399,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.081552',
     'ticker_sentiment_score': '-0.121393',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'I was mom-shamed for leaving my kids to go back to school. My partner was the one who defended my choice.',
   'url': 'https://www.businessinsider.com/mom-shamed-going-back-school-graduate-degree-2024-1',
   'time_published': '20240127T121900',
   'authors': ['joj'],
   'summary': 'I was mom-shamed for going back to school to get my graduate degree - Business Insider ...',
   'banner_image': None,
   'source': 'Business Insider',
   'category_within_source': 'GoogleRSS',
   'source_domain': 'www.businessinsider.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': -0.024475,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'META',
     'relevance_score': '0.124486',
     'ticker_sentiment_score': '-0.046386',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '3 Conclusive Reasons Global-e Online Could Explode Higher in 2024',
   'url': 'https://www.fool.com/investing/2024/01/27/3-conclusive-reasons-global-e-online-could-explode/',
   'time_published': '20240127T121000',
   'authors': ['Nicholas Robbins'],
   'summary': "Discover how Global-e Online's success in 2023 could drive it to even greater heights.",
   'banner_image': 'https://g.foolcdn.com/editorial/images/762041/business-person-businesswoman-cardboard-box-computer-delivering-e-commerce.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.108179'}],
   'overall_sentiment_score': 0.467902,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'SHOP',
     'relevance_score': '0.196212',
     'ticker_sentiment_score': '0.372422',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'GLBE',
     'relevance_score': '0.098862',
     'ticker_sentiment_score': '0.230059',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Trump faces two-front fight as Biden and Haley hit campaign trail | Politics',
   'url': 'https://www.cnn.com/2024/01/27/politics/biden-haley-trump-election-campaign/index.html',
   'time_published': '20240127T120000',
   'authors': ['Eric Bradner'],
   'summary': 'Trump faces two-front fight as Biden and Haley hit campaign trail ...',
   'banner_image': 'https://media.cnn.com/api/v1/images/stellar/prod/240126195659-01-nikki-haley-012624.jpg?q=w_1110,c_fill',
   'source': 'CNN',
   'category_within_source': 'Economy',
   'source_domain': 'www.cnn.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.09636,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'FOX',
     'relevance_score': '0.020615',
     'ticker_sentiment_score': '-0.037269',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Apple iPhone 16 Pro Max: New Report Claims Bold Upgrade Coming',
   'url': 'https://www.forbes.com/sites/davidphelan/2024/01/27/apple-iphone-16-pro-max-new-report-claims-bold-upgrade-coming/',
   'time_published': '20240127T120000',
   'authors': ['David Phelan'],
   'summary': "Cameras are a key component on every smartphone, and it looks like the next iPhones will see a photographic improvement, at least in the larger version of the Pro iPhone released this fall, the iPhone 16 Pro Max. Here's what's coming.",
   'banner_image': 'https://imageio.forbes.com/specials-images/imageserve/650c35cc398d11ecff40a341/0x0.jpg?format=jpg&crop=2014,1343,x0,y83,safe&height=900&width=1600&fit=bounds',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.415966,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'AWON',
     'relevance_score': '0.103331',
     'ticker_sentiment_score': '0.425515',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'WB',
     'relevance_score': '0.103331',
     'ticker_sentiment_score': '0.141874',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Samsung Makes Surprise New Offer To Galaxy S24 Buyers',
   'url': 'https://www.forbes.com/sites/jaymcgregor/2024/01/27/samsung-galaxy-s24-ultra-preorder-deal-free-galaxy-watch-6/',
   'time_published': '20240127T115700',
   'authors': ['Janhoi McGregor'],
   'summary': "This story was updated on January 27th. Update below. Not to be outshone by Google's aggressive new pricing strategy for its Pixel 8 range, Samsung is throwing new freebies and discounts at people who pre-order the Galaxy S24.",
   'banner_image': 'https://imageio.forbes.com/specials-images/imageserve/65b131ebe7ad502dbf6805b7/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.150201,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.044386',
     'ticker_sentiment_score': '0.077359',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'SSNLF',
     'relevance_score': '0.683587',
     'ticker_sentiment_score': '0.252826',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'GOOG',
     'relevance_score': '0.261584',
     'ticker_sentiment_score': '0.114685',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'AT&T Is Still a No-Brainer Value Stock to Buy in 2024',
   'url': 'https://www.fool.com/investing/2024/01/27/att-still-a-no-brainer-value-stock-to-buy-in-2024/',
   'time_published': '20240127T114000',
   'authors': ['Timothy Green'],
   'summary': "The telecom giant's fourth-quarter report didn't wow investors, but it was good enough.",
   'banner_image': 'https://g.foolcdn.com/editorial/images/762664/telecom-worker-woman-industrials-5g-tech-12.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.999986'},
    {'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '0.413559'}],
   'overall_sentiment_score': 0.164901,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'T',
     'relevance_score': '0.521465',
     'ticker_sentiment_score': '0.208435',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Pros and cons of moving from London to Australia, career change after burnout',
   'url': 'https://www.businessinsider.com/moving-london-melbourne-australia-career-change-pros-cons-2024-1?amp',
   'time_published': '20240127T113300',
   'authors': ['Madison Hoff'],
   'summary': 'Facebook Email icon An envelope. It indicates the ability to send an email. Email Twitter LinkedIn icon The word "in". LinkedIn An icon in the shape of an angle pointing down.',
   'banner_image': 'https://i.insider.com/65b3f0f76c8f0a134f7a4710?width=1200&format=jpeg',
   'source': 'Business Insider',
   'category_within_source': 'GoogleRSS',
   'source_domain': 'www.businessinsider.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.173133,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'META',
     'relevance_score': '0.03068',
     'ticker_sentiment_score': '0.10115',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'IBM Stock: Bull vs. Bear',
   'url': 'https://www.fool.com/investing/2024/01/27/ibm-stock-bull-vs-bear/',
   'time_published': '20240127T113000',
   'authors': ['Keith Noonan and Anders Bylund'],
   'summary': "Is IBM an undervalued AI stock that's ready for a big breakout?",
   'banner_image': 'https://g.foolcdn.com/editorial/images/761305/ai-on-a-cloud-icon.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.998356'},
    {'topic': 'Earnings', 'relevance_score': '0.714479'},
    {'topic': 'Mergers & Acquisitions', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.254361,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.040416',
     'ticker_sentiment_score': '0.306853',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'KD',
     'relevance_score': '0.040416',
     'ticker_sentiment_score': '-0.129248',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '2 Growth Stocks to Buy and Hold for the Next 10 Years',
   'url': 'https://www.fool.com/investing/2024/01/27/2-growth-stocks-to-buy-and-hold-for-the-next-10-ye/',
   'time_published': '20240127T111700',
   'authors': ['Matthew Frankel', 'CFP®'],
   'summary': 'These two companies have massive long-term potential and look attractive at the current prices.',
   'banner_image': 'https://g.foolcdn.com/editorial/images/762559/mobile-payment-2022-b.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'IPO', 'relevance_score': '0.158519'},
    {'topic': 'Financial Markets', 'relevance_score': '0.214378'},
    {'topic': 'Earnings', 'relevance_score': '0.310843'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.296451,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'RBLX',
     'relevance_score': '0.367141',
     'ticker_sentiment_score': '0.280008',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'SQ',
     'relevance_score': '0.2256',
     'ticker_sentiment_score': '0.109808',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Google Update Reveals AI Will Start Reading All Your Private Messages',
   'url': 'https://www.forbes.com/sites/zakdoffman/2024/01/27/new-details-free-ai-upgrade-for-google-and-samsung-android-users-leaks/',
   'time_published': '20240127T111527',
   'authors': ['Zak Doffman'],
   'summary': "Google has just unveiled a game-changing AI upgrade for Android. But it has a darker side. Google's AI will start to read and analyze your private messages, going back forever. So what does this mean for you, how do you maintain your privacy, and when does it begin.",
   'banner_image': 'https://imageio.forbes.com/specials-images/imageserve/65b41420a2b346798e66d370/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds',
   'source': 'Forbes',
   'category_within_source': 'n/a',
   'source_domain': 'www.forbes.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.097432,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'GOOG',
     'relevance_score': '0.348374',
     'ticker_sentiment_score': '0.087006',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "1 Magnificent Vanguard ETF I'm Buying Hand Over Fist in 2024",
   'url': 'https://www.fool.com/investing/2024/01/27/1-magnificent-vanguard-etf-im-buying-in-2024/',
   'time_published': '20240127T110000',
   'authors': ['Katie Brockman'],
   'summary': 'With the right strategy, this investment could help you earn well over $1 million.',
   'banner_image': 'https://g.foolcdn.com/editorial/images/761983/person-looking-at-a-laptop-and-holding-a-book.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '1.0'},
    {'topic': 'Financial Markets', 'relevance_score': '1.0'}],
   'overall_sentiment_score': 0.247261,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.059785',
     'ticker_sentiment_score': '0.126507',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Video appears to show Ukraine's new 'Ironclad' drone vehicle machine-gunning a Russian outpost",
   'url': 'https://www.businessinsider.com/ukraine-ironclad-drone-machine-gunning-russian-outpost-video-2024-1',
   'time_published': '20240127T105300',
   'authors': ['Nathan Rennolds'],
   'summary': "Ukraine's futuristic 'Ironclad' combat drone vehicle enters Russia war: Video - Business Insider ...",
   'banner_image': None,
   'source': 'Business Insider',
   'category_within_source': 'GoogleRSS',
   'source_domain': 'www.businessinsider.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': -0.180075,
   'overall_sentiment_label': 'Somewhat-Bearish',
   'ticker_sentiment': [{'ticker': 'WBD',
     'relevance_score': '0.074926',
     'ticker_sentiment_score': '-0.066449',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'META',
     'relevance_score': '0.074926',
     'ticker_sentiment_score': '-0.213567',
     'ticker_sentiment_label': 'Somewhat-Bearish'}]},
  {'title': "WWE's Vince McMahon resigns after sexual assault and trafficking lawsuit",
   'url': 'https://www.aljazeera.com/news/2024/1/27/wwes-vince-mcmahon-resigns-after-sexual-assault-and-trafficking-lawsuit',
   'time_published': '20240127T105026',
   'authors': ['Al Jazeera'],
   'summary': 'Former employee files lawsuit accusing McMahon and another executive of sexual assault, trafficking and emotional abuse. Vince McMahon has resigned from wrestling giant TKO Group and the subsidiary World Wrestling Entertainment ( WWE ) he founded after a lawsuit that accused him of sexual assault ...',
   'banner_image': 'https://www.aljazeera.com/wp-content/uploads/2024/01/2022-04-04T044456Z_1039529791_MT1USATODAY18017453_RTRMADP_3_WRESTLING-WWE-WRESTLEMANIA-1706349783.jpg?resize=770%2C513&quality=80',
   'source': 'Al Jareeza',
   'category_within_source': 'n/a',
   'source_domain': 'www.aljazeera.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '1.0'}],
   'overall_sentiment_score': -0.076183,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'NFLX',
     'relevance_score': '0.084722',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'TKO',
     'relevance_score': '0.329551',
     'ticker_sentiment_score': '0.02702',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Forget Tesla: Consider These 2 Millionaire-Maker Stocks to Buy Instead',
   'url': 'https://www.fool.com/investing/2024/01/27/forget-tesla-consider-millionaire-maker-stock/',
   'time_published': '20240127T141000',
   'authors': ['Jeremy Bowman'],
   'summary': 'Tesla issued another disappointing earnings report.',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762605%2Ftesla-model-3.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.54554'},
    {'topic': 'Manufacturing', 'relevance_score': '0.5'},
    {'topic': 'Earnings', 'relevance_score': '0.999691'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.270969,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'META',
     'relevance_score': '0.059341',
     'ticker_sentiment_score': '0.073009',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NVDA',
     'relevance_score': '0.397697',
     'ticker_sentiment_score': '0.315126',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'TSLA',
     'relevance_score': '0.628304',
     'ticker_sentiment_score': '0.328455',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'GM',
     'relevance_score': '0.448513',
     'ticker_sentiment_score': '0.329127',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': "Nvidia Is Selling $10 Billion in GPUs to This AI Tech Giant  ( Hint: It's Not Microsoft ) ",
   'url': 'https://www.fool.com/investing/2024/01/27/nvidia-selling-billion-gpu-ai-tech-giant-microsoft/',
   'time_published': '20240127T132000',
   'authors': ['Leo Sun'],
   'summary': "Meta Platforms is going all-in on Nvidia's H100 GPUs through the end of the year.",
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762450%2Fit-professionals-datacenter.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.161647'},
    {'topic': 'Manufacturing', 'relevance_score': '0.5'},
    {'topic': 'Earnings', 'relevance_score': '0.77141'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.1131,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.144853',
     'ticker_sentiment_score': '0.048974',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOG',
     'relevance_score': '0.144853',
     'ticker_sentiment_score': '0.086605',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'META',
     'relevance_score': '0.096866',
     'ticker_sentiment_score': '0.099171',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NVDA',
     'relevance_score': '0.41608',
     'ticker_sentiment_score': '0.056438',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'BGXX',
     'relevance_score': '0.048523',
     'ticker_sentiment_score': '-0.011888',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Down 82%, 1 Warren Buffett Growth Stock to Buy in 2024',
   'url': 'https://www.fool.com/investing/2024/01/27/down-82-1-warren-buffett-growth-stock-to-buy/',
   'time_published': '20240127T130000',
   'authors': ['Keith Noonan'],
   'summary': "The most explosive stock in Berkshire's portfolio today might be one you've never heard of.",
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F760806%2Fbuffett13-tmf.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.99977'},
    {'topic': 'Earnings', 'relevance_score': '0.904684'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Finance', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.18107,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'STNE',
     'relevance_score': '0.585442',
     'ticker_sentiment_score': '0.302328',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'BRK-A',
     'relevance_score': '0.149346',
     'ticker_sentiment_score': '0.141777',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '3 Top Growth Stocks to Buy Hand Over Fist in February',
   'url': 'https://www.fool.com/investing/2024/01/27/3-top-growth-stocks-buy-hand-over-fist-february/',
   'time_published': '20240127T125800',
   'authors': ['Jeremy Bowman', 'and Jennifer Saibil', 'John Ballard'],
   'summary': 'These companies have the qualities of long-term winners, and their stocks sell at a big discount right now.',
   'banner_image': 'https://g.foolcdn.com/editorial/images/762635/stock-chart-moving-up-making-money.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'IPO', 'relevance_score': '0.158519'},
    {'topic': 'Retail & Wholesale', 'relevance_score': '0.5'},
    {'topic': 'Financial Markets', 'relevance_score': '0.54554'},
    {'topic': 'Earnings', 'relevance_score': '0.928769'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.278108,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'NFLX',
     'relevance_score': '0.040622',
     'ticker_sentiment_score': '0.377983',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'CPNG',
     'relevance_score': '0.201021',
     'ticker_sentiment_score': '0.255115',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'TOST',
     'relevance_score': '0.389485',
     'ticker_sentiment_score': '0.109438',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Could PDD  ( Pinduoduo )  Become the Next Amazon?',
   'url': 'https://www.fool.com/investing/2024/01/27/could-pdd-pinduoduo-become-the-next-amazon/',
   'time_published': '20240127T123600',
   'authors': ['Leo Sun'],
   'summary': 'Investors should pay close attention to this rapidly growing e-commerce leader.',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762049%2Fwoman-box-items.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Earnings', 'relevance_score': '0.999921'},
    {'topic': 'Retail & Wholesale', 'relevance_score': '0.5'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.186477,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'BABA',
     'relevance_score': '0.321273',
     'ticker_sentiment_score': '0.27127',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'GOOG',
     'relevance_score': '0.047185',
     'ticker_sentiment_score': '-0.038979',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMZN',
     'relevance_score': '0.785986',
     'ticker_sentiment_score': '0.35606',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': 'Where Will Apple Stock Be in 5 Years?',
   'url': 'https://www.fool.com/investing/2024/01/27/where-will-apple-stock-be-in-5-years/',
   'time_published': '20240127T121000',
   'authors': ['Harsh Chauhan'],
   'summary': 'The tech giant could deliver much stronger growth over the next five years.',
   'banner_image': 'https://media.ycharts.com/charts/0d853029cf1f9b45434b166678913738.png',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.986714'},
    {'topic': 'Earnings', 'relevance_score': '0.998682'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Finance', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.312217,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'SSNLF',
     'relevance_score': '0.082111',
     'ticker_sentiment_score': '0.154415',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'AAPL',
     'relevance_score': '0.672608',
     'ticker_sentiment_score': '0.505785',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'BAC',
     'relevance_score': '0.04111',
     'ticker_sentiment_score': '0.190455',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'XIACY',
     'relevance_score': '0.082111',
     'ticker_sentiment_score': '0.154415',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'MS',
     'relevance_score': '0.04111',
     'ticker_sentiment_score': '-0.045257',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'A handful of space companies are running out of cash and time. Here are three at risk',
   'url': 'https://www.cnbc.com/2024/01/27/three-space-companies-at-risk-of-running-out-of-cash.html',
   'time_published': '20240127T120001',
   'authors': ['Michael Sheetz'],
   'summary': 'While many space companies battened the hatches to survive, a few publicly-traded names are running on fumes.',
   'banner_image': 'https://image.cnbcfm.com/api/v1/image/107361706-1705675765584-gettyimages-544312837-1935803.jpeg?v=1705675890&w=750&h=422&vtcrop=y',
   'source': 'CNBC',
   'category_within_source': 'Business',
   'source_domain': 'www.cnbc.com',
   'topics': [{'topic': 'IPO', 'relevance_score': '0.451494'},
    {'topic': 'Financial Markets', 'relevance_score': '0.54554'},
    {'topic': 'Manufacturing', 'relevance_score': '0.5'},
    {'topic': 'Earnings', 'relevance_score': '0.77141'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': -0.026121,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'SATL',
     'relevance_score': '0.113329',
     'ticker_sentiment_score': '-0.010267',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'SIDU',
     'relevance_score': '0.056808',
     'ticker_sentiment_score': '-0.02',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MNTS',
     'relevance_score': '0.224383',
     'ticker_sentiment_score': '-0.114656',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'PTAIF',
     'relevance_score': '0.113329',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'VORBQ',
     'relevance_score': '0.056808',
     'ticker_sentiment_score': '-0.178982',
     'ticker_sentiment_label': 'Somewhat-Bearish'},
    {'ticker': 'AWON',
     'relevance_score': '0.056808',
     'ticker_sentiment_score': '0.035196',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'LLAP',
     'relevance_score': '0.113329',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'The No. 1 reasons investors fail in the long run',
   'url': 'https://www.marketwatch.com/story/the-no-1-reasons-investors-fail-in-the-long-run-bf8229bf',
   'time_published': '20240127T120000',
   'authors': ['Paul A. Merriman'],
   'summary': 'How to overcome investing hurdles ...',
   'banner_image': 'https://images.mktw.net/im-42969640/social',
   'source': 'MarketWatch',
   'category_within_source': 'Top Stories',
   'source_domain': 'www.marketwatch.com',
   'topics': [{'topic': 'Retail & Wholesale', 'relevance_score': '0.5'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Financial Markets', 'relevance_score': '0.795202'}],
   'overall_sentiment_score': 0.12134,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.082677',
     'ticker_sentiment_score': '-0.127797',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOG',
     'relevance_score': '0.082677',
     'ticker_sentiment_score': '-0.127797',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMZN',
     'relevance_score': '0.082677',
     'ticker_sentiment_score': '-0.127797',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': 'Should You Buy the Dogs of the Dow in 2024?',
   'url': 'https://www.fool.com/investing/2024/01/27/should-you-buy-the-dogs-of-the-dow-in-2024/',
   'time_published': '20240127T115900',
   'authors': ['Jeremy Bowman'],
   'summary': 'The popular dividend-investing strategy has been around for years. Is it right for you?',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762238%2Fman-holding-cash-dividends.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'Life Sciences', 'relevance_score': '0.5'},
    {'topic': 'Financial Markets', 'relevance_score': '0.989041'},
    {'topic': 'Earnings', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.192136,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'KVUE',
     'relevance_score': '0.064797',
     'ticker_sentiment_score': '0.134527',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'VZ',
     'relevance_score': '0.129168',
     'ticker_sentiment_score': '0.089459',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMGN',
     'relevance_score': '0.064797',
     'ticker_sentiment_score': '0.134527',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'JNJ',
     'relevance_score': '0.064797',
     'ticker_sentiment_score': '0.134527',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Some baby brands have a cult-like following. Kyte Baby's went sour | Business",
   'url': 'https://edition.cnn.com/2024/01/27/business/baby-brands-loyalty-kyte/index.html',
   'time_published': '20240127T113000',
   'authors': ['Ramishah Maruf'],
   'summary': "Some baby brands have a cult-like following. Kyte Baby's went sour CNN International ...",
   'banner_image': 'https://media.cnn.com/api/v1/images/stellar/prod/unknown-20240124131902903.jpeg?q=w_1110,c_fill',
   'source': 'CNN',
   'category_within_source': 'Economy',
   'source_domain': 'edition.cnn.com',
   'topics': [{'topic': 'Retail & Wholesale', 'relevance_score': '0.5'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.152806,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'META',
     'relevance_score': '0.067632',
     'ticker_sentiment_score': '0.04424',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'DBI',
     'relevance_score': '0.033846',
     'ticker_sentiment_score': '0.03198',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Some baby brands have a cult-like following. Kyte Baby's went sour | Business",
   'url': 'https://www.cnn.com/2024/01/27/business/baby-brands-loyalty-kyte/index.html',
   'time_published': '20240127T113000',
   'authors': ['Ramishah Maruf'],
   'summary': "Some baby brands have a cult-like following. Kyte Baby's went sour ...",
   'banner_image': 'https://media.cnn.com/api/v1/images/stellar/prod/unknown-20240124131902903.jpeg?q=w_1110,c_fill',
   'source': 'CNN',
   'category_within_source': 'Markets',
   'source_domain': 'www.cnn.com',
   'topics': [{'topic': 'Retail & Wholesale', 'relevance_score': '0.5'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.152806,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'META',
     'relevance_score': '0.067632',
     'ticker_sentiment_score': '0.04424',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'DBI',
     'relevance_score': '0.033846',
     'ticker_sentiment_score': '0.03198',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '2 International Tech Stocks Poised for a Long-Awaited Comeback in 2024',
   'url': 'https://www.fool.com/investing/2024/01/27/2-international-tech-stocks-long-awaited-comeback/',
   'time_published': '20240127T111500',
   'authors': ['Will Healy'],
   'summary': 'These stocks prospered during the last bull market and could do so again.',
   'banner_image': 'https://g.foolcdn.com/editorial/images/762241/2024-down-the-road.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'IPO', 'relevance_score': '0.310843'},
    {'topic': 'Financial Markets', 'relevance_score': '0.266143'},
    {'topic': 'Earnings', 'relevance_score': '0.98396'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Finance', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.150333,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'MELI',
     'relevance_score': '0.054732',
     'ticker_sentiment_score': '0.053',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'SE',
     'relevance_score': '0.369163',
     'ticker_sentiment_score': '0.134338',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'STNE',
     'relevance_score': '0.369163',
     'ticker_sentiment_score': '0.216252',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'BRK-A',
     'relevance_score': '0.054732',
     'ticker_sentiment_score': '0.357004',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': 'My Top Bull Market Growth Stocks to Buy in 2024',
   'url': 'https://www.fool.com/investing/2024/01/27/my-top-bull-market-growth-stocks-to-buy-in-2024/',
   'time_published': '20240127T111000',
   'authors': ['Adria Cimino'],
   'summary': 'These stocks have advanced but still have plenty of room to run.',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762626%2Fgettyimages-bull-stock-market-charts.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.158519'},
    {'topic': 'Retail & Wholesale', 'relevance_score': '0.5'},
    {'topic': 'Financial Markets', 'relevance_score': '0.796627'},
    {'topic': 'Earnings', 'relevance_score': '0.999992'},
    {'topic': 'Technology', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.362561,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '0.282234',
     'ticker_sentiment_score': '0.367897',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'AMZN',
     'relevance_score': '0.320453',
     'ticker_sentiment_score': '0.347799',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Remark  ( NASDAQ:MARK )  Coverage Initiated by Analysts at StockNews.com',
   'url': 'https://www.defenseworld.net/2024/01/27/remark-nasdaqmark-coverage-initiated-by-analysts-at-stocknews-com-2.html',
   'time_published': '20240127T110649',
   'authors': ['Defense World Staff'],
   'summary': "StockNews.com assumed coverage on shares of Remark ( NASDAQ:MARK - Free Report ) in a research note released on Saturday morning. The firm issued a sell rating on the information services provider's stock. MARK opened at $0.36 on Friday. Remark has a 52-week low of $0.32 and a 52-week high of ...",
   'banner_image': 'https://www.americanbankingnews.com/wp-content/timthumb/timthumb.php?src=https://www.marketbeat.com/logos/remark-holdings-inc-logo.jpg?v=20221222093948&w=240&h=240&zc=2',
   'source': 'Stocknews.com',
   'category_within_source': 'n/a',
   'source_domain': 'www.defenseworld.net',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.87644'},
    {'topic': 'Earnings', 'relevance_score': '0.714479'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Finance', 'relevance_score': '0.5'}],
   'overall_sentiment_score': 0.390695,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'III',
     'relevance_score': '0.418689',
     'ticker_sentiment_score': '0.448996',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'STT',
     'relevance_score': '0.174587',
     'ticker_sentiment_score': '0.250656',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'BAC',
     'relevance_score': '0.087824',
     'ticker_sentiment_score': '0.184782',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'VIRT',
     'relevance_score': '0.087824',
     'ticker_sentiment_score': '0.184782',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'MARK',
     'relevance_score': '0.87744',
     'ticker_sentiment_score': '0.619491',
     'ticker_sentiment_label': 'Bullish'}]},
  {'title': 'TELUS  ( NYSE:TU )  Downgraded by StockNews.com to "Sell"',
   'url': 'https://www.defenseworld.net/2024/01/27/telus-nysetu-downgraded-by-stocknews-com-to-sell.html',
   'time_published': '20240127T105847',
   'authors': ['Defense World Staff'],
   'summary': 'TELUS ( NYSE:TU - Get Free Report ) ( TSE:T ) was downgraded by analysts at StockNews.com from a "hold" rating to a "sell" rating in a research report issued to clients and investors on Saturday. Other research analysts have also issued reports about the stock.',
   'banner_image': 'https://www.marketbeat.com/logos/telus-co-logo-1200x675.jpg',
   'source': 'Stocknews.com',
   'category_within_source': 'n/a',
   'source_domain': 'www.defenseworld.net',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.998962'},
    {'topic': 'Earnings', 'relevance_score': '0.857896'},
    {'topic': 'Technology', 'relevance_score': '0.5'},
    {'topic': 'Finance', 'relevance_score': '0.5'},
    {'topic': 'Blockchain', 'relevance_score': '0.310843'}],
   'overall_sentiment_score': 0.357935,
   'overall_sentiment_label': 'Bullish',
   'ticker_sentiment': [{'ticker': 'BAC',
     'relevance_score': '0.072',
     'ticker_sentiment_score': '0.049492',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'TU',
     'relevance_score': '0.072',
     'ticker_sentiment_score': '0.181448',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'JPM',
     'relevance_score': '0.072',
     'ticker_sentiment_score': '0.049492',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CRYPTO:BTC',
     'relevance_score': '0.072',
     'ticker_sentiment_score': '0.181448',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Better Growth Stock: UnitedHealth Group vs. Johnson & Johnson',
   'url': 'https://www.fool.com/investing/2024/01/27/better-growth-stock-unitedhealth-group-vs-johnson/',
   'time_published': '20240127T151500',
   'authors': ['David Jagielski'],
   'summary': 'These companies have been focusing on growing their operations, but which stock is likely to provide investors with better returns?',
   'banner_image': 'https://g.foolcdn.com/editorial/images/762088/a-doctor-looking-at-a-tablet-with-another-person.jpg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Life Sciences', 'relevance_score': '0.333333'},
    {'topic': 'Financial Markets', 'relevance_score': '0.214378'},
    {'topic': 'Earnings', 'relevance_score': '0.961735'},
    {'topic': 'Mergers & Acquisitions', 'relevance_score': '0.360215'},
    {'topic': 'Technology', 'relevance_score': '0.333333'},
    {'topic': 'Finance', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.240472,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'KVUE',
     'relevance_score': '0.063091',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMAM',
     'relevance_score': '0.063091',
     'ticker_sentiment_score': '0.141107',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'UNH',
     'relevance_score': '0.473427',
     'ticker_sentiment_score': '0.489705',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'JNJ',
     'relevance_score': '0.365166',
     'ticker_sentiment_score': '0.24848',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': "Psyched: Suggestibility And Psychedelics' Effects, EU's $7M Research Fund, Australia's Treatment Delivery, BZ Podcast And More - ATAI Life Sciences  ( NASDAQ:ATAI ) , Clearmind Medicine  ( NASDAQ:CMND ) ",
   'url': 'https://www.benzinga.com/markets/cannabis/24/01/36814962/psyched-suggestibility-and-psychedelics-effects-eus-7m-research-fund-australias-treatment-delive',
   'time_published': '20240127T150018',
   'authors': ['Lara Goldstein'],
   'summary': 'A new study led by Balázs Szigeti and with involvement of researchers Brandon Weiss, Fernando E Rosas, David Erritzoe, David Nutt and Robin Carhart-Harris found evidence of suggestibility predicting an antidepressant response for patients receiving psilocybin therapy.',
   'banner_image': 'https://cdn.benzinga.com/files/images/story/2024/Psyched.png?width=1200&height=800&fit=crop',
   'source': 'Benzinga',
   'category_within_source': 'Markets',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Life Sciences', 'relevance_score': '0.333333'},
    {'topic': 'Financial Markets', 'relevance_score': '0.87644'},
    {'topic': 'Manufacturing', 'relevance_score': '0.333333'},
    {'topic': 'Technology', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.071122,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'DRUG',
     'relevance_score': '0.09239',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'IXHL',
     'relevance_score': '0.183546',
     'ticker_sentiment_score': '0.18278',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'CMPS',
     'relevance_score': '0.138198',
     'ticker_sentiment_score': '-0.062971',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'ENVB',
     'relevance_score': '0.09239',
     'ticker_sentiment_score': '-0.114703',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MNMD',
     'relevance_score': '0.138198',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CMND',
     'relevance_score': '0.09239',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'SEEL',
     'relevance_score': '0.09239',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'SILO',
     'relevance_score': '0.09239',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': "Apple, Tesla, Amazon And Dogecoin Will Hit 10 Cents On Hopes Of Musk's X Payment Integration, Says Analyst: Bulls And Bears",
   'url': 'https://www.benzinga.com/news/large-cap/24/01/36812015/benzinga-bulls-and-bears-apple-tesla-amazon-and-dogecoin-will-hit-10-cents-on-hopes-of-musks-x-pay',
   'time_published': '20240127T142626',
   'authors': ['Michael Cohen'],
   'summary': "Benzinga examined the prospects for many investors' favorite stocks over the last week - here's a look at some of our top stories.",
   'banner_image': 'https://cdn.benzinga.com/files/images/story/2024/01/26/bulls_bears3.png?width=1200&height=800&fit=crop',
   'source': 'Benzinga',
   'category_within_source': 'Trading',
   'source_domain': 'www.benzinga.com',
   'topics': [{'topic': 'Economy - Monetary', 'relevance_score': '0.682689'},
    {'topic': 'Retail & Wholesale', 'relevance_score': '0.333333'},
    {'topic': 'Financial Markets', 'relevance_score': '0.962106'},
    {'topic': 'Manufacturing', 'relevance_score': '0.333333'},
    {'topic': 'Earnings', 'relevance_score': '0.158519'},
    {'topic': 'Technology', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.139692,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'AMD',
     'relevance_score': '0.198493',
     'ticker_sentiment_score': '0.148673',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NVDA',
     'relevance_score': '0.198493',
     'ticker_sentiment_score': '0.148673',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AAPL',
     'relevance_score': '0.1331',
     'ticker_sentiment_score': '0.21297',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'TSLA',
     'relevance_score': '0.198493',
     'ticker_sentiment_score': '-0.380117',
     'ticker_sentiment_label': 'Bearish'},
    {'ticker': 'AMZN',
     'relevance_score': '0.1331',
     'ticker_sentiment_score': '0.275516',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'CRYPTO:BTC',
     'relevance_score': '0.198493',
     'ticker_sentiment_score': '0.079097',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'CRYPTO:DOGE',
     'relevance_score': '0.198493',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '5 Phenomenal Stocks I Just Bought That You Should Consider Too',
   'url': 'https://www.fool.com/investing/2024/01/27/5-phenomenal-stocks-i-just-bought/',
   'time_published': '20240127T134700',
   'authors': ['Keithen Drury'],
   'summary': "Even though the stock market just hit new highs, I'm still buying.",
   'banner_image': 'https://media.ycharts.com/charts/a3ced5c8cafa03e1af7e2a8db60bf485.png',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Retail & Wholesale', 'relevance_score': '0.333333'},
    {'topic': 'Financial Markets', 'relevance_score': '0.413559'},
    {'topic': 'Manufacturing', 'relevance_score': '0.333333'},
    {'topic': 'Earnings', 'relevance_score': '0.998947'},
    {'topic': 'Technology', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.304687,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'PATH',
     'relevance_score': '0.192694',
     'ticker_sentiment_score': '0.276889',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'SHOP',
     'relevance_score': '0.048621',
     'ticker_sentiment_score': '0.084124',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'GOOG',
     'relevance_score': '0.192694',
     'ticker_sentiment_score': '-0.050307',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'MELI',
     'relevance_score': '0.285526',
     'ticker_sentiment_score': '0.239029',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'SPOT',
     'relevance_score': '0.048621',
     'ticker_sentiment_score': '0.084124',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'NKE',
     'relevance_score': '0.048621',
     'ticker_sentiment_score': '0.084124',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMZN',
     'relevance_score': '0.285526',
     'ticker_sentiment_score': '0.24414',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': "3 Stocks Warren Buffett Sold in 2023, and the 1 Stock He Couldn't Get Enough Of",
   'url': 'https://www.fool.com/investing/2024/01/27/stocks-warren-buffett-sold-2023-and-stock-bought/',
   'time_published': '20240127T122200',
   'authors': ['Adam Levy'],
   'summary': "Should investors follow Buffett into one of the few stocks he's been buying recently?",
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F762348%2Fbuffett2-tmf.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Financial Markets', 'relevance_score': '0.996023'},
    {'topic': 'Energy & Transportation', 'relevance_score': '0.333333'},
    {'topic': 'Technology', 'relevance_score': '0.333333'},
    {'topic': 'Finance', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.119968,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'MSFT',
     'relevance_score': '0.048523',
     'ticker_sentiment_score': '0.0',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'OXY',
     'relevance_score': '0.096866',
     'ticker_sentiment_score': '0.365576',
     'ticker_sentiment_label': 'Bullish'},
    {'ticker': 'CVX',
     'relevance_score': '0.373611',
     'ticker_sentiment_score': '0.13346',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'BRK-A',
     'relevance_score': '0.096866',
     'ticker_sentiment_score': '0.165924',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': "Is Growth Your New Year's Resolution? This Unstoppable Warren Buffett Index Fund Could Turn $75 a month into $50,000",
   'url': 'https://www.fool.com/investing/2024/01/27/for-growth-try-unstoppable-buffett-index-fund/',
   'time_published': '20240127T121500',
   'authors': ['Adria Cimino'],
   'summary': 'The strategy of monthly investing can work for any budget.',
   'banner_image': 'https://g.foolcdn.com/editorial/images/762324/slide-1-warren-buffett-source-motley-fool.jpeg',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Retail & Wholesale', 'relevance_score': '0.333333'},
    {'topic': 'Financial Markets', 'relevance_score': '0.995015'},
    {'topic': 'Technology', 'relevance_score': '0.333333'},
    {'topic': 'Finance', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': 0.333821,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'AAPL',
     'relevance_score': '0.053509',
     'ticker_sentiment_score': '0.130705',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'AMZN',
     'relevance_score': '0.053509',
     'ticker_sentiment_score': '0.130705',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'BRK-A',
     'relevance_score': '0.053509',
     'ticker_sentiment_score': '0.229834',
     'ticker_sentiment_label': 'Somewhat-Bullish'}]},
  {'title': 'Could IonQ Become the Next Snowflake?',
   'url': 'https://www.fool.com/investing/2024/01/27/could-ionq-stock-become-next-snowflake/',
   'time_published': '20240127T120000',
   'authors': ['Leo Sun'],
   'summary': 'Will this quantum computing company become the next high-growth cloud play?',
   'banner_image': 'https://g.foolcdn.com/image/?url=https%3A%2F%2Fg.foolcdn.com%2Feditorial%2Fimages%2F761865%2Foptical-circuits.jpg&op=resize&w=700',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'IPO', 'relevance_score': '0.451494'},
    {'topic': 'Financial Markets', 'relevance_score': '0.161647'},
    {'topic': 'Earnings', 'relevance_score': '0.858979'},
    {'topic': 'Real Estate & Construction', 'relevance_score': '0.333333'},
    {'topic': 'Technology', 'relevance_score': '0.333333'},
    {'topic': 'Finance', 'relevance_score': '0.333333'}],
   'overall_sentiment_score': -0.019307,
   'overall_sentiment_label': 'Neutral',
   'ticker_sentiment': [{'ticker': 'SNOW',
     'relevance_score': '0.448842',
     'ticker_sentiment_score': '0.056396',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'BRK-A',
     'relevance_score': '0.052801',
     'ticker_sentiment_score': '0.082999',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'IONQ',
     'relevance_score': '0.710675',
     'ticker_sentiment_score': '-0.057895',
     'ticker_sentiment_label': 'Neutral'}]},
  {'title': '7 Stocks Ready for Dividend Hikes in 2024',
   'url': 'https://www.fool.com/investing/2024/01/27/7-stocks-ready-for-dividend-hikes-in-2024/',
   'time_published': '20240127T110500',
   'authors': ['Matthew DiLallo'],
   'summary': 'These companies appear poised to give their investors a sizable raise this year.',
   'banner_image': 'https://media.ycharts.com/charts/b745d805fb5dd4e97ac1586c5a81dd73.png',
   'source': 'Motley Fool',
   'category_within_source': 'n/a',
   'source_domain': 'www.fool.com',
   'topics': [{'topic': 'Technology', 'relevance_score': '0.2'},
    {'topic': 'Finance', 'relevance_score': '0.2'},
    {'topic': 'Retail & Wholesale', 'relevance_score': '0.2'},
    {'topic': 'Financial Markets', 'relevance_score': '0.360215'},
    {'topic': 'Manufacturing', 'relevance_score': '0.2'},
    {'topic': 'Earnings', 'relevance_score': '0.999938'},
    {'topic': 'Real Estate & Construction', 'relevance_score': '0.2'}],
   'overall_sentiment_score': 0.331217,
   'overall_sentiment_label': 'Somewhat-Bullish',
   'ticker_sentiment': [{'ticker': 'DMPZF',
     'relevance_score': '0.043979',
     'ticker_sentiment_score': '0.114919',
     'ticker_sentiment_label': 'Neutral'},
    {'ticker': 'VMW',
     'relevance_score': '0.043979',
     'ticker_sentiment_score': '0.210462',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'AVGO',
     'relevance_score': '0.174587',
     'ticker_sentiment_score': '0.260639',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'FDS',
     'relevance_score': '0.087824',
     'ticker_sentiment_score': '0.252059',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'PLD',
     'relevance_score': '0.174587',
     'ticker_sentiment_score': '0.163777',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'ICE',
     'relevance_score': '0.174587',
     'ticker_sentiment_score': '0.176484',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'EQIX',
     'relevance_score': '0.131403',
     'ticker_sentiment_score': '0.164426',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'PAYC',
     'relevance_score': '0.087824',
     'ticker_sentiment_score': '0.160271',
     'ticker_sentiment_label': 'Somewhat-Bullish'},
    {'ticker': 'DPZ',
     'relevance_score': '0.087824',
     'ticker_sentiment_score': '0.120792',
     'ticker_sentiment_label': 'Neutral'}]}]}